[package]
name = "thousandfold"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = {
  version = "0.19.1",
  default-features = false,
  features = ["3d", "audio", "dev", "ui"],
}
log = {
  version = "*",
  features = ["max_level_debug", "release_max_level_warn"],
}

automoduse = { version = "*" }
extfn = { version = "0.1.3" }

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

float_cmp = "allow"
large_enum_variant = "allow"
must_use_candidate = "allow"
needless_pass_by_value = "allow"
new_without_default = "allow"
suboptimal_flops = "allow"

allow_attributes = "deny"
definition_in_module_root = "deny"
self_named_module_files = "deny"
unwrap_used = "deny"

[profile.dev]
opt-level = 1
debug = "line-tables-only"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
codegen-units = 1
