msrv = "1.98"

allow-unwrap-in-tests = true
# Bevy types get long
type-complexity-threshold = 400

standard-macro-braces = [
  { name = "children", brace = "[" },  # TODO: others could use this too
]

disallowed-types = [
  { path = "std::collections::HashMap", reason = "use bevy::utils::HashMap instead" },
  { path = "std::collections::HashSet", reason = "use bevy::utils::HashSet instead" },
]

# 64 bit CPUs
trivial-copy-size-limit = 16
# Internal-only project and code
avoid-breaking-exported-api = false
